### ISSUE TITLE
Exclude some programs

### ISSUE THREAD

**Issue by notesbancales** [khanhas/AppVolumePlugin#1]
Hello, great work, i was looking for something like this since win10 releases !
I have a request, is it possible to include a easy way to exclude programs in the .ini ?
I see explorer and rainmeter.
Is there a way to set the max number of programs displayed ?

**Comment by khanhas** [comment]
1) Excluding apps seems possible. I will try my best and push it in next version.
2) If you're using my example skin, you can change the `MeasureName` in `[GeneratorScript]` to another measure that have number value is your desired maximum number.
```ini
[MaximumNumber]
Measure = Calc
Formula = 5

[GeneratorScript]
Measure=Script
ScriptFile  = GeneratorScript.lua
IncFile = MeasuresAndMeters.inc
MeasureName = MaximumNumber
```

If you're building your own skin, please post it here so I can take a look and might have solution.

**Comment by notesbancales** [comment]
The new release just did everything like I wanted ! Much Thanks !
