### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Mor3bane** [khanhas/AppVolumePlugin#2]
Whilst running appvolume 1.1 I noticed that over time - and by way of association my memory usage spiked over the course of 24 hours. This included even more in swap memory. Eventually I got a memory hex code and Rainmeter shut down.
Even since I restarted I am seeing an increase in swap usage and lack of it returning to normal as usual when certain programs are closed after being done with them - games for example.
If i get the pop up again i will screenshot it.
Hopefully you still monitor this.

**Comment by Mor3bane** [comment]
Just now I started appvolume1.1 and my swap usage just spike by 2 gig!! it is NOT going down so it is not an incidental spike.

**Comment by Mor3bane** [comment]
Hello again, I am back to ask another question - in the hopes you will respond...
How could "master" volume be added as an option to this?
I am having loads of fun messing around, but I cannot figure out the "master" volume.
Any help would be appreciated!

**Comment by khanhas** [comment]
Hi, I'm investigating + refactoring part of my code so hang on.
About master volume, you can use Rainmeter in-built Win7Audio plugin: https://docs.rainmeter.net/manual-beta/plugins/win7audio/

**Comment by Mor3bane** [comment]
Awesome!

**Comment by Mor3bane** [comment]
> Hi, I'm investigating + refactoring part of my code so hang on.
> About master volume, you can use Rainmeter in-built Win7Audio plugin: https://docs.rainmeter.net/manual-beta/plugins/win7audio/

Hey khanhas, thanks for coming in. I am lost on implementing the win7audio plugin within your structure e.g. having your bars show the master volume.
I understand the basic of the win7audio plugin but not in this format.
What I mean is I dont know where to start...
Should I build it in the S[n] K[n] section, or create a meter?
My attempts are not working. I wont annoy you with the incorrect code :P 
Thanks for any help!

**Comment by khanhas** [comment]
[AppVolumeExampleSkin.zip](https://github.com/khanhas/AppVolumePlugin/files/2451149/AppVolumeExampleSkin.zip)
Try this one.   

Basically, I made a shape and a text meter that have same styles as Apps, then put it on top of apps meters. In shape meter, I used `MasterVolCalc` as scale value instead of `AppVolXX` as other apps.
I also expanded background, modified position of generated meters (`S3K3`).

![image](https://user-images.githubusercontent.com/26436809/46546949-b9d32c80-c8f4-11e8-9df2-05607bb845a5.png)

**Comment by Mor3bane** [comment]
Thanks, now it seems so obvious - I was over complicating things.

THANKS for the help khanhas.

**Comment by khanhas** [comment]
Also, try this plugin version and tell me if it's still leaking memory:
[AppVolume_x64_dll.zip](https://github.com/khanhas/AppVolumePlugin/files/2451262/AppVolume_x64_dll.zip)
Extracts the dll to `%appdata%\Rainmeter\Plugins\`
Remember to exit Rainmeter first.

**Comment by Mor3bane** [comment]
Well, I see an immediate difference in Physical Memory being more stable. Swap 'may' still be leaking, and without chrome running Swap looked pretty good, but it jumped a bit high after chrome opened - which is weird since i am not running a tab with sound - I'll try that now... I opened Netflix and there was no spike worth mentioning. 
If anything looks gooey after a while, I'll update you.

This thing is SO COOL for Rainmeter. I can make it prettier than "sndvol.exe" and it functions the same - which is what makes your plugin totally worth keeping up on screen. (I have 6 1920x1080's so my Rainmeter is running tonnes of things...)

Thanks again khanhas!

**Comment by Mor3bane** [comment]
![untitled](https://user-images.githubusercontent.com/43879659/46549026-13971f00-c914-11e8-807d-2c3ec2d537bc.jpg)

**Comment by khanhas** [comment]
Fixed in v1.2.0
