### ISSUE TITLE
Administrator Permission Applications Not Responding to AppVol

### ISSUE THREAD

**Issue by Mor3bane** [khanhas/AppVolumePlugin#4]
Hi Khanhas,
I am having trouble getting apps that require administrator permission to be recognised by AppVol.

Is this something you have looked at yet?

Please let me know.
Thanks,
Mor

**Comment by Mor3bane** [comment]
Running Rainmeter as Administrator solved this.

**Comment by khanhas** [comment]
Well, user shouldn't need to run Rainmeter as Admin for it to work correctly all the time
I will investigate this later.

**Comment by Mor3bane** [comment]
Most excellent as usual. Your persistence is admirable. :)

**Comment by Mor3bane** [comment]
I noticed some behaviour that may help you resolve this in your dll.

Running Rainmeter as admin does resolve the problem, but there is a couple ways I tried to get this all automatic so to speak.

I tried creating a scheduled task to run rainmeter as admin at startup - this allowed your AppVol to see the admin requiring app. However, the app (which is SWTOR) would not fully load to the main program, but AppVol DID see it...

So I found that starting rainmeter as admin allows both AppVol and SWTOR to run correctly and SWTOR does not ask for admin approval - but rainmeter did initially.

Hope these behaviours assist you in coding around this.

I look forward to your next iteration of AppVol 1.3 😃

**Comment by Mor3bane** [comment]
Oh, forgot to say that I am using rainmeter to trigger SWTOR with a standard path to the main exe.

**Comment by khanhas** [comment]
https://github.com/khanhas/AppVolumePlugin/releases/tag/1.2.3
Try it out

**Comment by Mor3bane** [comment]
You are a wizard! It seems to be recognising the admin reqs now. I haven't extensively tested it yet, but at first glance, it is perfect.

By the way, what are you using to create your vcxproj? Is that visual c++ or something else?

**Comment by khanhas** [comment]
Visual Studio 2017  
If you're going to learn how to make plugin, you should use one of these projecttemplate and learn how to create one later: https://github.com/rainmeter/rainmeter-plugin-sdk/tree/master/C%2B%2B

**Comment by Mor3bane** [comment]
Hi khanhas
I hate to bug you again but since I love love your appvolume I would like to request another fix.
There still seems to be a memory leak. What is happening is when appvolume is running, is my physical memory demand goes up and eventually my swap is maxed out requiring a restart.
I hope you can find what it is.
Thanks

**Comment by Mor3bane** [comment]
Hey, khanhas, its me again.
Technical issue with the shape meter - the master volume does not like having a rounded edge - it just stays barely rounded and nothing seems to be able to change it beyond a minor rounding of the corner rather than being like a half circle on the end of the shape.

Suggestions?

**Comment by Mor3bane** [comment]
Hey, I just noticed that the scaled bars change as they extend to full length and flatten out at lower levels - I will experiment, but I hope you can help narrow down where that is happening.

Thanks.
