### ISSUE TITLE
Sill leaking memory

### ISSUE THREAD

**Issue by Mor3bane** [khanhas/AppVolumePlugin#6]
Hi khanhas
I hate to bug you again but since I love love your appvolume I would like to request another fix.
There still seems to be a memory leak. What is happening is when appvolume is running, is my physical memory demand goes up and eventually my swap is maxed out requiring a restart.
I hope you can find what it is.
Thanks

_Originally posted by @Mor3bane in https://github.com/khanhas/AppVolumePlugin/issues/4#issuecomment-464345958_

**Comment by khanhas** [comment]
Thank for your report and support, man. Really appreciated it.
I monitored Rainmeter for 20 minutes with [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) tool, but I didn't find any trace of memory leak or hog.

**Comment by Mor3bane** [comment]
Hey thanks for checking. My phys runs roughly at 50% but swap seems to run high at roughly 65%. Maybe that is just what my rig looks like. There are other applications running in this scenario, but they are trusted to be good at this point. It seems to slowly climb higher over time - like days but ya.
Thanks again for looking into it.

**Comment by Mor3bane** [comment]
Hey, I read up on swap memory and one of the causes was a hot rig. So I popped open the case and dusted the thing out. Seems that was my issue.
Thanks.
