### ISSUE TITLE
Is it possible to select a specific app instead of blacklisting everything except that app?

### ISSUE THREAD

**Issue by Tarimaru** [khanhas/AppVolumePlugin#8]
I want to select only spotify for volume control and then distribut the suite. It would be unpractical for every casual user of the suit to blacklist everything else that could register. Is it possible by setting the max number?

**Comment by khanhas** [comment]
I guess `AppName` option in child measure would fit your need?
Did you try it?
```ini
[SpotifyVolume]
Measure = Plugin
Plugin = AppVolume
Parent = AppVolumeParent
AppName = Spotify.exe
NumType = Volume
```

**Comment by Tarimaru** [comment]
Thanks for the help. I didn´t know if this was possible. Now it works exactly the way i wanted it to.
